### ISSUE TITLE
Missing/Wrong Keyword

### ISSUE THREAD

**Issue by brato** [Infineon/TLE493D-3DMagnetic-Sensor#19]
Hi,

no biggie but I think the `getNorm` https://github.com/Infineon/TLE493D-3DMagnetic-Sensor/blob/011f268583dfa4c88883c2ca28a0f71317e46e24/src/Tle493d.h#L147 function is missing in the keywords.txt and the `getAmount` function is nowhere to be found in the Code. So this line https://github.com/Infineon/TLE493D-3DMagnetic-Sensor/blob/011f268583dfa4c88883c2ca28a0f71317e46e24/keywords.txt#L28 should be changed to `getNorm`.

**Comment by 9Volts9er** [comment]
Hi,
thanks for reporting this issue, I fixed it with the latest [commit](https://github.com/Infineon/TLE493D-3DMagnetic-Sensor/commit/20369645e3badaff2ed807453d40de1c5467c626).

I will close this issue, but feel free to reopen it, if the problem still exists.
