### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [Infineon/TLE493D-3DMagnetic-Sensor#3]
In the file "TLE493D-W2B6-3DMagnetic-Sensor/src/util/BusInterface.cpp" in the function readout(), there is a Wire.endTransmission() after the Wire.requestFrom(). That Wire.endTransmission() at the end of the function can be removed.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by sherylll** [comment]
https://github.com/Infineon/TLE493D-W2B6-3DMagnetic-Sensor/commits/master/src/util/BusInterface.cpp
